version: '3.7'

services:

  db:
    image: postgres:12.1-alpine
    volumes:
      - pgdata_volume:/var/lib/postgresql/data/
    ports:
      - 5440:5432
    environment:
      - POSTGRES_DB=junior_tasks
      - POSTGRES_USER=junior_tasks
      - POSTGRES_PASSWORD=junior_tasks_pass
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  pgdata_volume:
