# Generated by Django 4.2.4 on 2023-10-02 09:21

import app.constants
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category_name_en', models.TextField()),
                ('category_name_kz', models.TextField()),
                ('category_name_ru', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('due', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE'), ('REJECTED_BY_CHILD', 'REJECTED_BY_CHILD'), ('REJECTED_BY_PARENT', 'REJECTED_BY_PARENT'), ('PAID', 'PAID')], default=app.constants.TaskStatus['ACTIVE'], max_length=32)),
                ('parent_id', models.CharField(max_length=32)),
                ('child_id', models.CharField(max_length=32)),
                ('iban', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='PredefinedTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_en', models.TextField()),
                ('name_kz', models.TextField()),
                ('name_ru', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel')),
            ],
            options={
                'verbose_name': 'Predefined Task',
                'verbose_name_plural': 'Predefined Tasks',
            },
        ),
    ]
